language: objective-c
osx_image: xcode9.3
branches:
  only:
    - master
notifications:
  email: false
install:
  - brew install clang-format
script:
  - xcodebuild -workspace objc_utils_mac.xcworkspace -scheme objc_utils_mac_tests -configuration Debug OBJROOT=build -sdk macosx clean test
  - xcodebuild -workspace objc_utils_ios.xcworkspace -scheme objc_utils_ios_tests -configuration Debug OBJROOT=build -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' clean test
